#!/usr/bin/python3
def raise_exception():
    print(10 + "test")
